# Generated by Django 2.2.7 on 2019-11-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=300)),
                ('vote_count', models.IntegerField(default=0)),
                ('views', models.CharField(max_length=50)),
            ],
        ),
    ]
